# Generated by Django 5.2.8 on 2026-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderproduct_order_alter_orderproduct_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentData",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="paymentError",
            field=models.BooleanField(default=False),
        ),
    ]
