# Generated by Django 5.2.8 on 2025-12-13 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_specification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
    ]
