# Generated by Django 5.2.8 on 2025-12-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name_plural": "Images"},
        ),
    ]
