# Generated by Django 5.2.8 on 2025-12-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
    ]
