# Generated by Django 5.2.8 on 2025-12-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_image_options_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.subcategory",
            ),
        ),
    ]
