# Generated by Django 5.2.8 on 2025-12-21 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_tag_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limitedEdition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="sortIndex",
            field=models.SmallIntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ],
            ),
        ),
    ]
