# Generated by Django 5.2.8 on 2025-12-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_basket_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="session_key",
        ),
    ]
