# Generated by Django 5.2.8 on 2026-01-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_remove_basket_session_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                unique=True,
            ),
        ),
    ]
