# Generated by Django 5.2.8 on 2026-01-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_alter_basket_id_alter_basketitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="basketitem",
            unique_together={("basket", "product")},
        ),
    ]
